[project]
name = "broadway"
version = "0.1.0"
description = "Generalized ML experimentation platform"
requires-python = ">=3.12"

dependencies = [
    "lightgbm>=4.7.0",
    "optuna>=4.4.0",
    "pandas>=2.3.0",
    "pyarrow>=19",
    "psycopg[binary]>=3.3.0",
    "pydantic>=2.11.0",
    "pyyaml>=6.0.0",
    "scikit-learn>=1.7.0",
    "scipy>=1.16.0",
    "sqlalchemy>=2.0.0",
    "tqdm>=4.66.0",
    "xgboost>=3.4.0",
    "joblib>=1.5.0",
    "kubernetes>=32.0.0",
    "python-dotenv>=1.1.0",
    "pytest>=8.4.0",
    "pingouin>=0.6.0",
    "statsmodels>=0.14.6",
    "matplotlib>=3.10.0",
    "requests>=2.32.0",
    "pandera>=0.32.1",
    "mlflow>=3.15.1",
    "polars>=1.43.2",
    "seaborn>=0.13.0",
    "shap>=0.46",
    "lime>=0.2",
    "optuna-integration[mlflow]>=4.9.0",
    "psycopg2-binary>=2.9",
]

[project.optional-dependencies]
spark = ["pyspark>=4.0.0"]
db = ["psycopg[binary]>=3.3.0", "sqlalchemy>=2.0.0"]
k8s = ["kubernetes>=32.0.0"]
all = ["broadway[spark,db,k8s]"]

[project.scripts]
ds-pipeline = "broadway.cli:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src", "."]
include = ["broadway*", "project*"]
